---
dist: trusty
language: java
jdk: oraclejdk8
script: ./docToolchain/bin/doctoolchain . generateHTML
deploy:
  local_dir: target/html5
  provider: pages
  skip_cleanup: true
  github_token: ${DEPLOY_GITHUB_TOKEN}
  keep_history: true
  on:
    branch: master
